name = "Havoc Realms S1"
author = "minecraftbossdj, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a636b568fe0a348c055d732de492e61ba83e27b160a9877c9cf26511438272b"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
